### ISSUE TITLE
Double '/' in path

### ISSUE THREAD

**Issue by scrwdnet** [spatie/temporary-directory#11] opened 2017-09-07 14:55 UTC
When using this package through Media Library I get a double slash in the path generated by this line:

https://github.com/spatie/temporary-directory/blob/master/src/TemporaryDirectory.php#L88

Removing the ` .DIRECTORY_SEPARATOR. ` part fixed it for me.

**Comment by AlexVanderbist** [comment] 2017-09-11 08:57
Hi! Thanks for reporting this. The issue is should be fixed in 1.1.3!

**Closed** 2017-09-11 08:59 UTC
